### ISSUE TITLE
Using rustfmt for managing import grouping and order

### ISSUE THREAD

**Issue by alexrutar** [autobib/autobib#41]
Once https://github.com/rust-lang/rustfmt/issues/5083 and https://github.com/rust-lang/rustfmt/issues/4991 are stabilized, we should create a `rustfmt.toml` file with contents
```toml
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
```
For now I guess we can just enforce these manually.
